# Generated by Django 4.2.6 on 2023-10-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='text_overlay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
