# Generated by Django 4.2.6 on 2023-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
