# Generated by Django 4.2.6 on 2023-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_uploadedimage_text_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='text_font',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='text_font_size',
            field=models.IntegerField(default=24),
        ),
    ]
