# Generated by Django 4.2.6 on 2023-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_uploadedimage_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='filter_effect',
            field=models.CharField(choices=[('gaussian', 'Gaussian Blur'), ('box', 'Box Blur'), ('unsharp', 'Unsharp Mask'), ('median', 'Median Filter'), ('min', 'Min Filter'), ('max', 'Max Filter')], default='gaussian', max_length=50),
        ),
    ]
