# Generated by Django 4.2.6 on 2023-10-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0003_uploadedimage_text_color_uploadedimage_text_font_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='text_font',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='text_font_size',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='text_overlay',
        ),
    ]
